# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GmailJob`.
# Please instead update this file by running `bin/tapioca dsl GmailJob`.


class GmailJob
  class << self
    sig { params(block: T.nilable(T.proc.params(job: GmailJob).void)).returns(T.any(GmailJob, FalseClass)) }
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
