# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `HackerNewsSiteJob`.
# Please instead update this file by running `bin/tapioca dsl HackerNewsSiteJob`.


class HackerNewsSiteJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: HackerNewsSiteJob).void)
      ).returns(T.any(HackerNewsSiteJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
